services:

  otel:
    image: otel/opentelemetry-collector-contrib:0.120.0

  chameleon:
    image: keeonline/chameleon:${BRANCH_NAME}-latest
    ports: 
      - localhost:18080:8080
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4318
    