name: Quebec service on push

on:
  push:
    branches:
      - main
        
jobs:
  build-on-push:
      runs-on: ubuntu-24.04
      steps:
        - name: salutation
          run: |
            echo This is on_push for quebec service. branch=${{ github.ref_name }}

        - name: Checkout sources
          uses: actions/checkout@v4

        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 22

        - name: Setup Gradle            
          uses: gradle/actions/setup-gradle@v4

        - name: Build with Gradle
          run: ./gradlew build

        - name: Upload build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: Reports
            path: build/reports

        - name: List files
          run: ls -lsa ./build/libs

        # run integration tests same as pull request

        # for main pushes - get semantic version and publish image

        - name: Build image
          run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/quebec:latest .  

        - name: Login to Docker registry
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            
        - name: Publish image
          run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/quebec:latest