name: Pull request

on:
  pull_request:
  
jobs:
  salutation:
      runs-on: ubuntu-24.04
      steps:
        - run: |
            echo This is on_pull_request for chameleon service

# add processing to build local image and run intergration tests using docker compose