name: Quebec service on push

on:
  push:
  
jobs:
  build-on-push:
      runs-on: ubuntu-24.04
      steps:
        - name: salutation
          run: |
            echo This is on_push for quebec service. branch=${{ github.ref_name }}
        - name: Checkout sources
          uses: actions/checkout@v4
        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 22
        - name: Setup Gradle            
          uses: gradle/actions/setup-gradle@v4
        - name: Build with Gradle
          run: ./gradlew build            