name: Run tests

on:
  workflow_dispatch:

jobs:
  execute:
    name: Run the service tests
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install docker compose
        run: |
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version
