name: Run the System Integration Tests

on:
  workflow_dispatch:

jobs:
  execute:
    name: Run the SITs
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Download the standalone karate jar
        run: |
          wget -O /opt/karate.jar https://github.com/karatelabs/karate/releases/download/v1.5.1/karate-1.5.1.jar

      - name: Execute the SITs using karate
        working-directory: sit/karate
        run: |
          java -jar /opt/karate.jar -h
  